import React from 'react'
export const metadata = {
    title: "Becoming seller",
    description: "Generated by create next app",
  };

function page() {
  return (
    <div>
      <h1>Becoming a seller</h1>
    </div>
  )
}

export default page
